import "./globals.css";
import Providers from "../../redux/Provider";
import HeaderLayout from "../components/Header/Header";

export const metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({ children }) {
   return (
      <html lang="en">
         <body>
            <Providers>
               <HeaderLayout />
               <main>{children}</main>
            </Providers>
         </body>
      </html>
   );
}
